language: cpp
dist: trusty

branches:
  except:
    - gh-pages

cache:
  apt: true
  directories:
    - '${TRAVIS_BUILD_DIR}/deps/doxygen'

matrix:
  include:
    # Default clang
    - compiler: clang
      env:
        - CCACHE_CPP2=yes
      script:
        - .ci/make_and_test.sh 11
        - .ci/make_and_test.sh 14 -DUNITS_HEADER_ONLY=ON
    #    - .ci/make_and_test.sh 14
    #    - .ci/make_and_test.sh 17
    # Docs and clang 3.5
    - compiler: clang
      env:
        - DEPLOY_MAT=yes
        - CCACHE_CPP2=yes
      addons:
        apt:
          packages:
            - clang-3.5
      install:
        - export CC=clang-3.5
        - export CXX=clang++-3.5
      script:
        - bash .ci/make_and_test.sh 11
      after_success:
        - export DOXYFILE=$TRAVIS_BUILD_DIR/docs/Doxyfile
        - export DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - |
          if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]
          then
          #  . .ci/build_doxygen.sh
           # .ci/build_docs.sh
          fi

      # GCC 7 and coverage (8 does not support lcov, wait till 9 and new lcov)
    - compiler: gcc
      env:
        - GCC_VER=7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - curl
            - lcov
      install:
        - export CC=gcc-7
        - export CXX=g++-7
        - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
        - cd $TRAVIS_BUILD_DIR
        - '. .ci/build_lcov.sh'
        - 'bash .ci/run_codecov.sh'
      script:
        - .ci/make_and_test.sh 11
        - .ci/make_and_test.sh 14
        - .ci/make_and_test.sh 17

      # GCC 4.8
    - compiler: gcc
      env:
        - GCC_VER=4.8
      addons:
        apt:
          packages:
            - g++-4.8
      install:
        - export CC=gcc-4.8
        - export CXX=g++-4.8
      script:
        - .ci/make_and_test.sh 11

install: skip

script:
  - .ci/make_and_test.sh 11
  - .ci/make_and_test.sh 14
